version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev_mongo
      MONGO_INITDB_ROOT_DATABASE: products
      MONGO_INITDB_ROOT_PASSWORD: dev_password
    ports:
      - "27777:27017"
    restart: always
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
