server:
  port: 8081
  contextPath: /api

spring:
  data:
    mongodb:
      uri: 'mongodb://dev_mongo:dev_password@localhost:27777/products'
      auto-index-creation: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
