server:
  port: 8081
  contextPath: /api

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/products
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
